from __future__ import annotations

import ast
import importlib
import json
import os
import re
import sys
import textwrap
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Set, Tuple

import typer

from .models import Segment
from .planning import LLMPlanner


class ModuleWriter:
    def __init__(self, add_banner: bool = True) -> None:
        self.add_banner = add_banner

    @staticmethod
    def _module_name_to_parts(module_name: str) -> List[str]:
        raw = str(module_name or "").strip()
        if not raw:
            return ["module"]

        if any(sep in raw for sep in (".", "/", "\\")):
            tokens = re.split(r"[./\\]+", raw)
            parts = [ModuleWriter._slugify(token) for token in tokens if token.strip()]
            return parts or ["module"]

        normalized = ModuleWriter._slugify(raw)
        if normalized == "main":
            return ["main"]
        if "_" in normalized:
            left, right = normalized.split("_", 1)
            return [left, ModuleWriter._slugify(right)]
        return [normalized]

    @classmethod
    def _module_name_to_import_path(cls, module_name: str) -> str:
        return ".".join(cls._module_name_to_parts(module_name))

    @classmethod
    def _module_name_to_relative_file(cls, module_name: str) -> str:
        return "/".join(cls._module_name_to_parts(module_name)) + ".py"

    @staticmethod
    def _written_file_to_module_path(filename: str) -> str:
        return ".".join(Path(filename).with_suffix("").parts)

    @staticmethod
    def _ensure_package_dirs(output_dir: Path, relative_filename: str) -> None:
        current = output_dir
        for part in Path(relative_filename).parts[:-1]:
            current = current / part
            current.mkdir(exist_ok=True)
            init_path = current / "__init__.py"
            if not init_path.exists():
                init_path.write_text("# Generated by pyfract\n", encoding="utf-8")

    @staticmethod
    def _prune_empty_package_dirs(output_dir: Path, relative_filename: str) -> None:
        current = (output_dir / Path(relative_filename)).parent
        while current != output_dir:
            init_path = current / "__init__.py"
            try:
                children = list(current.iterdir())
            except OSError:
                break
            remaining = [child for child in children if child != init_path]
            if remaining:
                break
            if init_path.exists():
                try:
                    init_path.unlink()
                except OSError:
                    break
            try:
                current.rmdir()
            except OSError:
                break
            current = current.parent

    @staticmethod
    def _build_relative_import(current_module_path: str, target_module_path: str, symbol: str) -> str:
        current_package_parts = [part for part in current_module_path.split(".")[:-1] if part]
        target_parts = [part for part in target_module_path.split(".") if part]
        shared = 0
        for current_part, target_part in zip(current_package_parts, target_parts):
            if current_part != target_part:
                break
            shared += 1

        climb = len(current_package_parts) - shared
        leading = "." * (climb + 1)
        remainder = ".".join(target_parts[shared:])
        module_ref = f"{leading}{remainder}" if remainder else leading
        return f"from {module_ref} import {symbol}"

    @staticmethod
    def _resolve_relative_module_name(current_module_path: str, target_module: Optional[str], level: int) -> str:
        current_package_parts = [part for part in current_module_path.split(".")[:-1] if part]
        climb = max(level - 1, 0)
        if climb >= len(current_package_parts):
            base_parts: List[str] = []
        else:
            base_parts = current_package_parts[: len(current_package_parts) - climb]
        if target_module:
            base_parts.extend(part for part in target_module.split(".") if part)
        return ".".join(base_parts)

    def _write_package_support_files(
        self,
        output_dir: Path,
        plan: Dict[str, Any],
        segments: Sequence[Segment],
        original_name: str,
        architecture_profile: str,
    ) -> None:
        if architecture_profile == "tool_cli":
            self._write_tool_cli_package_files(output_dir, plan, segments, original_name)
            return
        (output_dir / "__init__.py").write_text("# Generated by pyfract\n", encoding="utf-8")

    def _write_tool_cli_package_files(
        self,
        output_dir: Path,
        plan: Dict[str, Any],
        segments: Sequence[Segment],
        original_name: str,
    ) -> None:
        seg_map = {seg.identifier: seg for seg in segments}
        module_exports: Dict[str, List[str]] = {}
        cli_module_name = LLMPlanner._package_style_module_name("cli")

        for module in plan.get("modules", []):
            module_name = self._module_name_to_import_path(str(module.get("name", "")))
            exported_symbols: List[str] = []
            for seg_id in module.get("segment_ids", []):
                seg = seg_map.get(seg_id)
                if not seg:
                    continue
                if seg.kind in {"function", "async_function", "class"} and seg.name != "__main__":
                    exported_symbols.append(seg.name)
            module_exports[module_name] = list(dict.fromkeys(exported_symbols))
            if any(name in {"modularize", "version", "init_config"} for name in exported_symbols):
                cli_module_name = module_name

        init_lines = [
            f'"""Package generated from {original_name} by Pyfract."""',
            "",
        ]
        public_names: List[str] = []
        for module_name in sorted(module_exports):
            exports = module_exports[module_name]
            if not exports:
                continue
            safe_exports = [name for name in exports if re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", name)]
            if not safe_exports:
                continue
            init_lines.append(f"from .{module_name} import {', '.join(safe_exports)}")
            public_names.extend(safe_exports)

        if module_exports.get(cli_module_name):
            init_lines.append(f"from .{cli_module_name} import app")
            public_names.append("app")

        unique_public = list(dict.fromkeys(public_names))
        if unique_public:
            init_lines.extend(["", f"__all__ = {unique_public!r}"])
        else:
            init_lines.append("__all__ = []")
        init_lines.append("")
        (output_dir / "__init__.py").write_text("\n".join(init_lines), encoding="utf-8")

        main_lines = [
            "from . import app",
            "",
            'if __name__ == "__main__":',
            "    app()",
            "",
        ]
        (output_dir / "__main__.py").write_text("\n".join(main_lines), encoding="utf-8")

    @staticmethod
    def _strip_future_imports(code: str) -> Tuple[str, List[str]]:
        lines = code.splitlines(keepends=True)
        kept: List[str] = []
        futures: List[str] = []
        for line in lines:
            stripped = line.lstrip()
            if stripped.startswith("from __future__ import"):
                futures.append(line.strip())
            else:
                kept.append(line)
        return "".join(kept), futures

    @staticmethod
    def _merge_future_imports(chunks: List[str]) -> List[str]:
        seen: Set[str] = set()
        out: List[str] = []
        for chunk in chunks:
            if chunk not in seen:
                seen.add(chunk)
                out.append(chunk)
        return sorted(out)

    @staticmethod
    def _extract_future_imports(source_code: str) -> List[str]:
        return [
            line.strip()
            for line in source_code.splitlines()
            if line.lstrip().startswith("from __future__ import")
        ]

    def write(
        self,
        plan: Dict[str, Any],
        segments: Sequence[Segment],
        output_dir: Path,
        original_name: str,
        source_code: str,
        strict_validation: bool = False,
    ) -> Path:
        output_dir.mkdir(parents=True, exist_ok=True)
        architecture_profile = self._detect_architecture_profile_from_segments(segments)
        if architecture_profile == "application_runtime":
            plan = self._promote_runtime_architecture(plan, segments)
        elif architecture_profile == "tool_cli":
            plan = self._promote_tool_architecture(plan, segments)
        plan = self._merge_cyclic_modules(plan, segments)
        manifest_path = output_dir / "module_plan.json"
        previous_written_files: Set[str] = set()
        written_files: List[str] = []

        for _cycle_fix_pass in range(3):
            written_files = self._write_modules_once(
                plan=plan,
                segments=segments,
                output_dir=output_dir,
                original_name=original_name,
                source_code=source_code,
                previous_written_files=previous_written_files,
            )
            previous_written_files = set(written_files)

            import_cycles = self._detect_generated_import_cycles(output_dir, written_files)
            if not import_cycles:
                break

            typer.echo(
                "Detected generated import cycles; merging affected modules and rewriting package.",
                err=True,
            )
            plan = self._merge_modules_by_generated_cycles(plan, import_cycles)

        manifest_payload = {
            "original_file": original_name,
            "modules": plan.get("modules", []),
            "shared_helpers": plan.get("shared_helpers"),
            "notes": plan.get("notes"),
            "written_files": written_files,
        }
        manifest_path.write_text(json.dumps(manifest_payload, indent=2))
        self._write_package_support_files(
            output_dir=output_dir,
            plan=plan,
            segments=segments,
            original_name=original_name,
            architecture_profile=architecture_profile,
        )

        validation = self._validate_modules(output_dir, written_files)
        if strict_validation and not validation["all_valid"]:
            raise RuntimeError(
                f"Generated modules failed validation ({validation['passed']}/{validation['total']} passed)."
            )

        return manifest_path

    @staticmethod
    def _detect_architecture_profile_from_segments(segments: Sequence[Segment]) -> str:
        metadata = [
            {
                "kind": seg.kind,
                "name": seg.name,
                "defined_symbols": seg.defined_symbols,
                "signature_excerpt": seg.signature[:200],
            }
            for seg in segments
        ]
        return LLMPlanner._detect_architecture_profile(metadata)

    @staticmethod
    def _promote_tool_architecture(plan: Dict[str, Any], segments: Sequence[Segment]) -> Dict[str, Any]:
        seg_map = {seg.identifier: seg for seg in segments}
        buckets: Dict[str, List[str]] = {
            "models": [],
            "analysis": [],
            "planning": [],
            "writing": [],
            "cli": [],
            "shared": [],
        }

        for seg in segments:
            bucket = LLMPlanner._tool_cli_bucket(
                name=seg.name,
                kind=seg.kind,
                signature_excerpt=seg.signature[:200],
            )
            buckets.setdefault(bucket, []).append(seg.identifier)

        modules: List[Dict[str, Any]] = []
        for name, seg_ids in buckets.items():
            if not seg_ids:
                continue
            modules.append(
                {
                    "name": LLMPlanner._package_style_module_name(name),
                    "description": f"Tool architecture module for {name.replace('_', ' ')}.",
                    "segment_ids": sorted(seg_ids, key=lambda seg_id: seg_map[seg_id].start_line),
                }
            )

        new_plan = dict(plan)
        new_plan["modules"] = modules
        notes = str(plan.get("notes", "")).strip()
        extra = "Promoted tool architecture: layered modules for models, analysis, planning, writing, CLI, and shared code."
        new_plan["notes"] = f"{notes}\n{extra}".strip() if notes else extra
        return new_plan

    @staticmethod
    def _promote_runtime_architecture(plan: Dict[str, Any], segments: Sequence[Segment]) -> Dict[str, Any]:
        modules = [module for module in plan.get("modules", []) if isinstance(module, dict)]
        if not modules:
            return plan

        seg_map = {seg.identifier: seg for seg in segments}
        symbol_to_segment: Dict[str, str] = {}
        symbol_usage: Dict[str, int] = {}
        for seg in segments:
            for sym in seg.defined_symbols:
                symbol_to_segment.setdefault(sym, seg.identifier)
            for dep in seg.dependencies:
                symbol_usage[dep] = symbol_usage.get(dep, 0) + 1

        def is_startup_segment(seg: Segment) -> bool:
            code = seg.code
            return (
                "bot.run(" in code
                or 'TOKEN not found in environment variables' in code
                or "Starting Auraxis Bot" in code
                or 'print("=" * 50)' in code
            )

        def is_runtime_seed(seg: Segment) -> bool:
            lowered = seg.name.lower()
            code = seg.code.lower()
            if lowered in {"on_ready", "on_message", "get_prefix", "get_guild_prefix", "channel_command_gate"}:
                return True
            if any(
                token in lowered
                for token in [
                    "load_",
                    "save_",
                    "json",
                    "config",
                    "data",
                    "prefix",
                    "channel",
                    "guild",
                    "normalize",
                    "duplicate",
                    "hindi",
                    "rank",
                    "apply_aura",
                    "log_aura_change",
                    "calculate_ai_aura",
                    "evaluate_toxic",
                    "bot",
                ]
            ):
                return True
            if any(
                token in code
                for token in [
                    "commands.bot(",
                    "discord.intents",
                    'os.getenv("token")',
                    "os.getenv('token')",
                    "openrouter_api_key",
                    "load_json_safe(",
                    "config_data =",
                    "aura_data =",
                    "global_data =",
                    "recent_messages =",
                ]
            ):
                return True
            if max((symbol_usage.get(sym, 0) for sym in seg.defined_symbols), default=0) >= 4:
                return True
            return False

        startup_ids: Set[str] = {seg.identifier for seg in segments if is_startup_segment(seg)}
        runtime_ids: Set[str] = {seg.identifier for seg in segments if is_runtime_seed(seg)}

        changed = True
        while changed:
            changed = False
            for seg_id in list(runtime_ids):
                seg = seg_map.get(seg_id)
                if not seg:
                    continue
                for dep in seg.dependencies:
                    target_id = symbol_to_segment.get(dep)
                    if target_id and target_id not in runtime_ids and target_id not in startup_ids:
                        runtime_ids.add(target_id)
                        changed = True

        runtime_ids.difference_update(startup_ids)
        if not runtime_ids:
            return plan

        existing_modules: List[Dict[str, Any]] = []
        used_names: Set[str] = set()
        for module in modules:
            cleaned_segment_ids = [
                seg_id
                for seg_id in module.get("segment_ids", [])
                if isinstance(seg_id, str) and seg_id not in runtime_ids and seg_id not in startup_ids
            ]
            if cleaned_segment_ids:
                updated = dict(module)
                updated["segment_ids"] = cleaned_segment_ids
                existing_modules.append(updated)
                used_names.add(str(updated.get("name", "")))

        runtime_name = LLMPlanner._package_style_module_name("runtime_core")
        main_name = "main"
        while runtime_name in used_names:
            runtime_name += "_1"
        used_names.add(runtime_name)
        while main_name in used_names:
            main_name += "_1"

        existing_modules.append(
            {
                "name": runtime_name,
                "description": "Runtime spine: bot object, shared state, bootstrap dependencies, and high-coupling core logic.",
                "segment_ids": sorted(runtime_ids, key=lambda seg_id: seg_map[seg_id].start_line),
            }
        )
        if startup_ids:
            existing_modules.append(
                {
                    "name": main_name,
                    "description": "Dedicated entrypoint module for startup checks and bot.run(...).",
                    "segment_ids": sorted(startup_ids, key=lambda seg_id: seg_map[seg_id].start_line),
                }
            )

        new_plan = dict(plan)
        new_plan["modules"] = existing_modules
        notes = str(plan.get("notes", "")).strip()
        extra = "Promoted runtime architecture: isolated runtime_core and main entrypoint before writing modules."
        new_plan["notes"] = f"{notes}\n{extra}".strip() if notes else extra
        return new_plan

    def _write_modules_once(
        self,
        plan: Dict[str, Any],
        segments: Sequence[Segment],
        output_dir: Path,
        original_name: str,
        source_code: str,
        previous_written_files: Set[str],
    ) -> List[str]:
        seg_map = {seg.identifier: seg for seg in segments}
        written_files: List[str] = []

        all_segment_ids = []
        for module in plan.get("modules", []):
            all_segment_ids.extend(module.get("segment_ids", []))
        if len(all_segment_ids) != len(set(all_segment_ids)):
            typer.echo("Warning: Duplicate segments detected in plan!", err=True)

        all_imports = self._extract_imports(source_code)
        names_from_imports = self._names_bound_by_imports(all_imports)
        dependency_errors = self._check_dependency_coverage(plan, segments, names_from_imports)
        for error in dependency_errors:
            typer.echo(f"Validation warning: {error}", err=True)

        symbol_to_slug: Dict[str, str] = {}
        ambiguous_symbols: Set[str] = set()
        for module in plan.get("modules", []):
            safe = self._module_name_to_import_path(str(module.get("name", "")))
            for seg_id in module.get("segment_ids", []):
                seg = seg_map.get(seg_id)
                if not seg:
                    continue
                for symbol in seg.defined_symbols:
                    if symbol in symbol_to_slug and symbol_to_slug[symbol] != safe:
                        ambiguous_symbols.add(symbol)
                    else:
                        symbol_to_slug[symbol] = safe
        for symbol in ambiguous_symbols:
            symbol_to_slug.pop(symbol, None)

        for module in plan.get("modules", []):
            raw_name = module["name"]
            safe_name = self._module_name_to_import_path(str(raw_name))
            relative_filename = self._module_name_to_relative_file(str(raw_name))
            target = output_dir / Path(relative_filename)
            self._ensure_package_dirs(output_dir, relative_filename)
            target.parent.mkdir(parents=True, exist_ok=True)
            written_files.append(relative_filename)

            module_code = ""
            module_dependencies = set()
            module_used_attributes: List[Tuple[str, str]] = []
            written_segment_ids = set()
            locally_defined: Set[str] = set()
            future_chunks: List[str] = []

            for seg_id in module.get("segment_ids", []):
                if seg_id in written_segment_ids:
                    typer.echo(f"Warning: Segment {seg_id} already written to module {raw_name}", err=True)
                    continue
                written_segment_ids.add(seg_id)

                seg = seg_map.get(seg_id)
                if not seg:
                    typer.echo(f"Warning: missing segment {seg_id}", err=True)
                    continue
                locally_defined.update(seg.defined_symbols)
                body, future_lines = self._strip_future_imports(seg.code)
                future_chunks.extend(future_lines)
                module_code += f"# --- segment {seg.identifier} ({seg.kind}) ---\n{body}\n\n"
                module_dependencies.update(seg.dependencies)
                module_used_attributes.extend(seg.used_attributes)

            global_future_lines = self._extract_future_imports(source_code)
            future_lines = self._merge_future_imports(future_chunks + global_future_lines)
            needed_imports = self._get_needed_imports(
                all_imports,
                module_code,
                module_dependencies,
                safe_name,
                used_attributes=module_used_attributes,
                symbol_to_slug=symbol_to_slug,
                locally_defined=locally_defined,
            )

            with target.open("w", encoding="utf-8") as handle:
                if self.add_banner:
                    handle.write(
                        textwrap.dedent(
                            f'''"""
                            Auto-generated module from {original_name}
                            Plan summary: {module.get("description","(no description)")}
                            """
                            '''
                        ).strip()
                        + "\n\n"
                    )
                if future_lines:
                    handle.write("\n".join(future_lines) + "\n\n")
                if needed_imports:
                    handle.write("\n".join(needed_imports) + "\n\n")
                handle.write(module_code)

        obsolete = previous_written_files - set(written_files)
        for filename in obsolete:
            target = output_dir / Path(filename)
            if target.exists():
                try:
                    target.unlink()
                    self._prune_empty_package_dirs(output_dir, filename)
                except OSError:
                    pass

        return written_files

    @staticmethod
    def _names_bound_by_imports(all_imports: List[Tuple[str, List[str]]]) -> Set[str]:
        return {name for _, names in all_imports for name in names}

    @staticmethod
    def _check_dependency_coverage(
        plan: Dict[str, Any],
        segments: Sequence[Segment],
        names_from_imports: Set[str],
    ) -> List[str]:
        errors: List[str] = []
        seg_map = {seg.identifier: seg for seg in segments}
        symbol_to_module: Dict[str, str] = {}
        for module in plan.get("modules", []):
            module_name = module.get("name", "unknown_module")
            for seg_id in module.get("segment_ids", []):
                seg = seg_map.get(seg_id)
                if seg:
                    for symbol in seg.defined_symbols:
                        symbol_to_module[symbol] = module_name

        for module in plan.get("modules", []):
            module_name = module.get("name", "unknown_module")
            local_symbols: Set[str] = set()
            external_deps: Set[str] = set()
            for seg_id in module.get("segment_ids", []):
                seg = seg_map.get(seg_id)
                if not seg:
                    continue
                local_symbols.update(seg.defined_symbols)
                for dep in seg.dependencies:
                    if dep not in local_symbols:
                        external_deps.add(dep)

            for dep in sorted(external_deps):
                if dep in names_from_imports:
                    continue
                target_module = symbol_to_module.get(dep)
                if target_module is None:
                    errors.append(f"Module '{module_name}' depends on '{dep}', but no module defines it.")
        return errors

    @staticmethod
    def _extract_imports(source_code: str) -> List[Tuple[str, List[str]]]:
        try:
            tree = ast.parse(source_code)
        except SyntaxError:
            return []

        imports = []
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    name = alias.asname if alias.asname else alias.name
                    import_stmt = f"import {alias.name}" + (f" as {alias.asname}" if alias.asname else "")
                    imports.append((import_stmt, [name]))
            elif isinstance(node, ast.ImportFrom):
                module_name = node.module or ""
                level_dots = "." * node.level
                from_part = f"from {level_dots}{module_name} import"

                imported_names = []
                for alias in node.names:
                    name = alias.asname if alias.asname else alias.name
                    imported_names.append(name)

                def _render_alias(alias: ast.alias) -> str:
                    return f"{alias.name} as {alias.asname}" if alias.asname else alias.name

                import_stmt = f"{from_part} {', '.join(_render_alias(alias) for alias in node.names)}"
                imports.append((import_stmt, imported_names))

        return imports

    def _get_needed_imports(
        self,
        all_imports: List[Tuple[str, List[str]]],
        module_code: str,
        dependencies: set,
        current_module_name: str,
        used_attributes: Optional[List[Tuple[str, str]]] = None,
        symbol_to_slug: Optional[Dict[str, str]] = None,
        locally_defined: Optional[Set[str]] = None,
    ) -> List[str]:
        if used_attributes is None:
            used_attributes = []
        if symbol_to_slug is None:
            symbol_to_slug = {}
        if locally_defined is None:
            locally_defined = set()

        attribute_names = {attr for _, attr in used_attributes}
        needed_imports = []

        cross_module_deps = {
            dep_name
            for dep_name in dependencies
            if dep_name not in locally_defined and dep_name in symbol_to_slug and symbol_to_slug.get(dep_name) != current_module_name
        }

        def _filter_import_stmt(import_stmt: str, keep_names: List[str]) -> Optional[str]:
            if not keep_names:
                return None
            if import_stmt.startswith("import "):
                parts = [part.strip() for part in import_stmt[7:].split(",")]
                kept = []
                for part in parts:
                    alias = part.split(" as ")[-1].strip()
                    base = part.split(" as ")[0].strip()
                    if alias in keep_names or base in keep_names:
                        kept.append(part)
                return "import " + ", ".join(kept) if kept else None
            if import_stmt.startswith("from ") and " import " in import_stmt:
                prefix, imported = import_stmt.rsplit(" import ", 1)
                parts = [part.strip() for part in imported.split(",")]
                kept = []
                for part in parts:
                    alias = part.split(" as ")[-1].strip()
                    base = part.split(" as ")[0].strip()
                    if alias in keep_names or base in keep_names:
                        kept.append(part)
                return f"{prefix} import {', '.join(kept)}" if kept else None
            return import_stmt

        for import_stmt, imported_names in all_imports:
            valid_names = [name for name in imported_names if name not in attribute_names]
            if not valid_names:
                continue

            keep_names = [name for name in valid_names if name not in cross_module_deps]
            import_needed = False

            for name in keep_names:
                pattern = r"\b" + re.escape(name) + r"\b"
                if re.search(pattern, module_code) and not self._is_in_comment(module_code, name):
                    import_needed = True
                    break
                if name in dependencies:
                    import_needed = True
                    break

            if import_needed:
                filtered = _filter_import_stmt(import_stmt, keep_names)
                if filtered:
                    needed_imports.append(filtered)

        for dep_name in sorted(dependencies):
            if dep_name in attribute_names or dep_name in locally_defined:
                continue
            target_slug = symbol_to_slug.get(dep_name)
            if not target_slug or target_slug == current_module_name:
                continue
            cross_import = self._build_relative_import(current_module_name, target_slug, dep_name)
            if cross_import not in needed_imports:
                needed_imports.append(cross_import)

        final_imports = []
        for import_stmt in needed_imports:
            imported_names = set()
            if import_stmt.startswith("from ") and " import " in import_stmt:
                _, right = import_stmt.rsplit(" import ", 1)
                for item in right.split(","):
                    item = item.strip()
                    if " as " in item:
                        imported_names.add(item.split(" as ")[-1].strip())
                    else:
                        imported_names.add(item)

            if not imported_names.intersection(locally_defined):
                final_imports.append(import_stmt)

        return final_imports

    @staticmethod
    def _is_in_comment(code: str, name: str) -> bool:
        lines = code.split("\n")
        for line in lines:
            code_part = line.split("#", 1)[0] if "#" in line else line
            pattern = r"\b" + re.escape(name) + r"\b"
            if re.search(pattern, code_part):
                return False
        return True

    @staticmethod
    def _parse_import_statement(import_stmt: str) -> List[str]:
        names = []
        import_stmt = import_stmt.strip()

        if import_stmt.startswith("import "):
            parts = import_stmt[7:].split(",")
            for part in parts:
                name = part.split(" as ")[0].strip()
                names.append(name.split(".")[-1])
        elif import_stmt.startswith("from ") and " import " in import_stmt:
            _, imports_part = import_stmt.split(" import ", 1)
            for item in imports_part.split(","):
                name = item.split(" as ")[0].strip()
                if name != "*":
                    names.append(name)

        return names

    @staticmethod
    def _detect_generated_import_cycles(output_dir: Path, written_files: List[str]) -> List[List[str]]:
        graph = ModuleWriter._build_generated_import_graph(output_dir, written_files)
        sccs = ModuleWriter._strongly_connected_components(graph)
        return [sorted(component) for component in sccs if len(component) > 1]

    @staticmethod
    def _build_generated_import_graph(output_dir: Path, written_files: List[str]) -> Dict[str, Set[str]]:
        graph: Dict[str, Set[str]] = {}
        module_names = {
            ModuleWriter._written_file_to_module_path(filename)
            for filename in written_files
            if filename.endswith(".py")
        }

        for filename in written_files:
            if not filename.endswith(".py"):
                continue
            module_name = ModuleWriter._written_file_to_module_path(filename)
            graph.setdefault(module_name, set())
            filepath = output_dir / Path(filename)
            try:
                tree = ast.parse(filepath.read_text(encoding="utf-8"))
            except SyntaxError:
                continue

            for node in ast.walk(tree):
                if not isinstance(node, ast.ImportFrom):
                    continue
                if node.level <= 0 or not node.module:
                    continue
                imported_module = ModuleWriter._resolve_relative_module_name(
                    current_module_path=module_name,
                    target_module=node.module,
                    level=node.level,
                )
                if imported_module in module_names and imported_module != module_name:
                    graph[module_name].add(imported_module)

        return graph

    def _merge_modules_by_generated_cycles(
        self,
        plan: Dict[str, Any],
        import_cycles: List[List[str]],
    ) -> Dict[str, Any]:
        modules = [module for module in plan.get("modules", []) if isinstance(module, dict)]
        if not modules or not import_cycles:
            return plan

        slug_to_module = {
            self._module_name_to_import_path(str(module.get("name", ""))): module
            for module in modules
        }
        merged_modules: List[Dict[str, Any]] = []
        merged_slugs: Set[str] = set()

        for cycle in import_cycles:
            cycle_modules = [slug_to_module[slug] for slug in cycle if slug in slug_to_module]
            if len(cycle_modules) < 2:
                continue

            merged_slugs.update(cycle)
            descriptions: List[str] = []
            merged_segment_ids: List[str] = []
            seen_segments: Set[str] = set()
            merged_name_parts: List[str] = []

            for module in cycle_modules:
                module_name = str(module.get("name", "")).strip()
                if module_name:
                    merged_name_parts.append(self._module_name_to_import_path(module_name))
                description = str(module.get("description", "")).strip()
                if description:
                    descriptions.append(description)
                for seg_id in module.get("segment_ids", []):
                    if isinstance(seg_id, str) and seg_id not in seen_segments:
                        seen_segments.add(seg_id)
                        merged_segment_ids.append(seg_id)

            merged_name = LLMPlanner._package_style_module_name(
                "_".join(part.replace(".", "_") for part in dict.fromkeys(merged_name_parts)) or "merged_cycle_module"
            )
            merged_modules.append(
                {
                    "name": merged_name,
                    "description": " / ".join(dict.fromkeys(descriptions)) or f"Merged generated import cycle: {', '.join(cycle)}",
                    "segment_ids": merged_segment_ids,
                }
            )

        final_modules: List[Dict[str, Any]] = []
        for module in modules:
            slug = self._module_name_to_import_path(str(module.get("name", "")))
            if slug not in merged_slugs:
                final_modules.append(module)
        final_modules.extend(merged_modules)

        merged_plan = dict(plan)
        merged_plan["modules"] = final_modules
        merged_notes = str(plan.get("notes", "")).strip()
        cycle_note = "Auto-merged modules to resolve generated import cycles."
        merged_plan["notes"] = f"{merged_notes}\n{cycle_note}".strip()
        return merged_plan

    @staticmethod
    def _sort_modules_for_validation(output_dir: Path, written_files: List[str]) -> List[str]:
        module_by_file = {
            filename: ModuleWriter._written_file_to_module_path(filename)
            for filename in written_files
            if filename.endswith(".py")
        }
        stems = set(module_by_file.values())
        if len(stems) <= 1:
            return list(written_files)

        graph: Dict[str, Set[str]] = {module_name: set() for module_name in stems}
        indegree: Dict[str, int] = {module_name: 0 for module_name in stems}

        for filename, stem in module_by_file.items():
            path = output_dir / Path(filename)
            try:
                tree = ast.parse(path.read_text(encoding="utf-8"))
            except (OSError, SyntaxError):
                continue
            for node in ast.walk(tree):
                if not isinstance(node, ast.ImportFrom):
                    continue
                if node.level <= 0 or not node.module:
                    continue
                dep = ModuleWriter._resolve_relative_module_name(stem, node.module, node.level)
                if dep not in stems or dep == stem:
                    continue
                if stem not in graph[dep]:
                    graph[dep].add(stem)
                    indegree[stem] = indegree.get(stem, 0) + 1

        queue = sorted([stem for stem in indegree if indegree[stem] == 0])
        order: List[str] = []
        while queue:
            node = queue.pop(0)
            order.append(node)
            for neighbor in sorted(graph.get(node, ())):
                indegree[neighbor] -= 1
                if indegree[neighbor] == 0:
                    queue.append(neighbor)
                    queue.sort()

        if len(order) != len(stems):
            return list(written_files)

        stem_to_file = {module_name: filename for filename, module_name in module_by_file.items()}
        return [stem_to_file[stem] for stem in order if stem in stem_to_file]

    @staticmethod
    def _strongly_connected_components(graph: Dict[str, Set[str]]) -> List[List[str]]:
        index: Dict[str, int] = {}
        lowlink: Dict[str, int] = {}
        stack: List[str] = []
        on_stack: Set[str] = set()
        result: List[List[str]] = []

        def strongconnect(node: str) -> None:
            index[node] = len(index)
            lowlink[node] = index[node]
            stack.append(node)
            on_stack.add(node)

            for neighbor in graph.get(node, set()):
                if neighbor not in index:
                    strongconnect(neighbor)
                    lowlink[node] = min(lowlink[node], lowlink[neighbor])
                elif neighbor in on_stack:
                    lowlink[node] = min(lowlink[node], index[neighbor])

            if lowlink[node] == index[node]:
                component: List[str] = []
                while True:
                    current = stack.pop()
                    on_stack.remove(current)
                    component.append(current)
                    if current == node:
                        break
                result.append(component)

        for node in graph:
            if node not in index:
                strongconnect(node)

        return result

    @staticmethod
    def _merge_cyclic_modules(plan: Dict[str, Any], segments: Sequence[Segment]) -> Dict[str, Any]:
        modules = [module for module in plan.get("modules", []) if isinstance(module, dict)]
        if not modules:
            return plan

        metadata = [{"segment_id": seg.identifier, "dependencies": seg.dependencies} for seg in segments]
        module_deps = LLMPlanner._build_module_dependencies({"modules": modules}, metadata)
        sccs = ModuleWriter._strongly_connected_components(module_deps)
        cyclic_groups = [sorted(component) for component in sccs if len(component) > 1]
        if not cyclic_groups:
            return plan

        module_map = {module["name"]: module for module in modules}
        merged_modules: List[Dict[str, Any]] = []
        merged_names: Set[str] = set()
        total_segments = sum(
            len([seg_id for seg_id in module.get("segment_ids", []) if isinstance(seg_id, str)])
            for module in modules
        )
        skipped_cycles: List[List[str]] = []

        for cycle in cyclic_groups:
            merged_segment_ids: List[str] = []
            seen_segments: Set[str] = set()
            descriptions: List[str] = []
            for module_name in cycle:
                module = module_map.get(module_name)
                if not module:
                    continue
                if desc := str(module.get("description", "")).strip():
                    descriptions.append(desc)
                for seg_id in module.get("segment_ids", []):
                    if seg_id not in seen_segments:
                        merged_segment_ids.append(seg_id)
                        seen_segments.add(seg_id)

            if len(cycle) > 3:
                skipped_cycles.append(cycle)
                continue
            if total_segments and len(merged_segment_ids) / total_segments > 0.35:
                skipped_cycles.append(cycle)
                continue

            merged_names.update(cycle)
            merged_modules.append(
                {
                    "name": LLMPlanner._package_style_module_name(
                        "_".join(module_name.replace(".", "_") for module_name in cycle)
                    ),
                    "description": " / ".join(dict.fromkeys(descriptions)) or f"Merged cyclic modules: {', '.join(cycle)}",
                    "segment_ids": merged_segment_ids,
                }
            )

        final_modules: List[Dict[str, Any]] = []
        for module in modules:
            if module["name"] not in merged_names:
                final_modules.append(module)
        final_modules.extend(merged_modules)

        merged_plan = dict(plan)
        merged_plan["modules"] = final_modules
        merged_notes = str(plan.get("notes", "")).strip()
        note_parts: List[str] = []
        merged_flat = sorted([name for group in cyclic_groups if group not in skipped_cycles for name in group])
        skipped_flat = sorted([name for group in skipped_cycles for name in group])
        if merged_flat:
            note_parts.append(f"Auto-merged cyclic modules: {', '.join(merged_flat)}.")
        if skipped_flat:
            note_parts.append(
                f"Preserved larger cyclic module groups to avoid collapsing the plan: {', '.join(skipped_flat)}."
            )
        if merged_notes:
            note_parts.insert(0, merged_notes)
        merged_plan["notes"] = "\n".join(note_parts)
        return merged_plan

    @staticmethod
    def _validate_modules(output_dir: Path, written_files: List[str]) -> Dict[str, Any]:
        typer.echo("Validating generated modules...", err=True)

        all_valid = True
        tested_modules: Dict[str, bool] = {}
        package_name = output_dir.name
        package_parent = str(output_dir.parent.resolve())
        enable_import_validation = os.environ.get("MODULIZER_IMPORT_VALIDATE", "").strip().lower() in {
            "1",
            "true",
            "yes",
            "on",
        }
        inserted_path = False
        if package_parent not in sys.path:
            sys.path.insert(0, package_parent)
            inserted_path = True

        try:
            ordered_files = ModuleWriter._sort_modules_for_validation(output_dir, written_files)
            for filename in ordered_files:
                filepath = output_dir / Path(filename)
                module_name = ModuleWriter._written_file_to_module_path(filename)
                fq_module_name = f"{package_name}.{module_name}"
                status = "⏳"
                error_msg = ""

                try:
                    code = filepath.read_text(encoding="utf-8")
                    ast.parse(code)
                    compile(code, str(filepath), "exec")
                    ModuleWriter._validate_relative_import_targets(
                        code=code,
                        output_dir=output_dir,
                        current_module_path=module_name,
                    )
                    if enable_import_validation:
                        sys.modules.pop(fq_module_name, None)
                        imported = importlib.import_module(fq_module_name)
                        importlib.reload(imported)
                    status = "✅"
                    tested_modules[module_name] = True
                except SyntaxError as exc:
                    status = "❌"
                    error_msg = f"Syntax error: {exc.msg} at line {exc.lineno}"
                    tested_modules[module_name] = False
                    all_valid = False
                except Exception as exc:
                    status = "❌"
                    error_msg = f"{type(exc).__name__}: {exc}"
                    tested_modules[module_name] = False
                    all_valid = False

                if error_msg:
                    typer.echo(f"{status} {filename} - {error_msg[:140]}", err=True)
                else:
                    typer.echo(f"{status} {filename} is valid and executable", err=True)

            import_cycles = ModuleWriter._detect_generated_import_cycles(output_dir, written_files)
            if import_cycles:
                all_valid = False
                cycle_info = ", ".join(" -> ".join(cycle + [cycle[0]]) for cycle in import_cycles)
                typer.echo(f"❌ Generated import cycles remain: {cycle_info}", err=True)
        finally:
            if inserted_path:
                try:
                    sys.path.remove(package_parent)
                except ValueError:
                    pass

        passed = sum(1 for value in tested_modules.values() if value)
        total = len(tested_modules)
        typer.echo(f"\nValidation summary: {passed}/{total} modules passed", err=True)

        if not all_valid:
            typer.echo("WARNING: Module validation revealed issues. Review errors above.", err=True)
        return {"all_valid": all_valid, "passed": passed, "total": total}

    @staticmethod
    def _validate_relative_import_targets(code: str, output_dir: Path, current_module_path: str) -> None:
        tree = ast.parse(code)

        for node in ast.walk(tree):
            if not isinstance(node, ast.ImportFrom):
                continue
            if node.level <= 0:
                continue

            target_module = node.module
            if not target_module:
                continue

            resolved = ModuleWriter._resolve_relative_module_name(
                current_module_path=current_module_path,
                target_module=target_module,
                level=node.level,
            )
            if not resolved:
                continue

            module_file = output_dir.joinpath(*resolved.split(".")).with_suffix(".py")
            package_init = output_dir.joinpath(*resolved.split("."), "__init__.py")
            if not module_file.exists() and not package_init.exists():
                raise ImportError(f"Relative import target '.{target_module}' not found in generated package")

    @staticmethod
    def _slugify(value: str) -> str:
        value = value.lower().strip()
        value = re.sub(r"[^a-z0-9]+", "_", value)
        value = re.sub(r"_+", "_", value).strip("_")
        return value or "module"
